import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import {Button} from 'antd'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1>Welcome to Movie List</h1>
      <p>This website is still under development</p>
      <Link href='/dashboard'>
        <Button className={styles.button} type="primary">Go to List Movie</Button>
      </Link>
      </main>
    </>
  )
}
